version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: mangos_backend
    restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    ports:
      - "8080:80"

networks:
  app-network:
    driver: bridge